apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: backend
    newName: docker.io/omarbesbes/efrei:backend
  - name: frontend
    newName: docker.io/omarbesbes/efrei:frontend
  - name: wrapper
    newName: docker.io/omarbesbes/efrei:wrapper

resources:
  - backend
  - elasticsearch
  - frontend
  - go-wrapper
  - minio
  - postgres
