apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          env:
            - name: MINIO_ROOT_USER
              value: 'minioadmin'
            - name: MINIO_ROOT_PASSWORD
              value: 'minioadmin'
          volumeMounts:
            - mountPath: /data
              name: minio-data
          ports:
            - containerPort: 9000
            - containerPort: 9090
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data-pvc
