apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - name: minio-api-port
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
    - name: minio-management-port
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002
