# elasticsearch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: efrei.azurecr.io/elasticsearch/elasticsearch:8.13.0
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 128Mi
          env:
            - name: xpack.security.enabled
              value: 'false'
            - name: discovery.type
              value: 'single-node'
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-data
          ports:
            - containerPort: 9200
            - containerPort: 9300
      imagePullSecrets:
        - name: efreireg
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: elastic-data-pvc
