name: Build and deploy to Azure Kubernetes Service

on:
  push:
    branches: [dev]

env:
  NGNIX_INGRESS_MANIFEST_URL: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: |
            ${{ vars.REGISTRY }}/backend:latest
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/backend:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/backend:buildcache,mode=max

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: |
            ${{ vars.REGISTRY }}/frontend:latest
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/frontend:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/frontend:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      actions: read
    environment: preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy NGINX Ingress Controller to ingress-nginx namespace
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.NGNIX_INGRESS_MANIFEST_URL }}
          namespace: ingress-nginx

      - name: Deploy platform
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: manifests
