name: Build and deploy to Azure Kubernetes Service

on:
  push:
    branches: [dev]

env:
  NGNIX_INGRESS_MANIFEST_URL: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: echo
        if: false
        run: echo
    outputs:
      registry: ${{ vars.REGISTRY }}
      docker-namespace: ${{ vars.DOCKER_NAMESPACE || 'efrei' }}

  build:
    runs-on: ubuntu-latest
    needs: prepare
    environment: preview
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./apps/frontend/Dockerfile
            image: ${{ needs.prepare.outputs.registry }}/${{ needs.prepare.outputs.docker-namespace }}/frontend
          - dockerfile: ./apps/backend/Dockerfile
            image: ${{ needs.prepare.outputs.registry }}/${{ needs.prepare.outputs.docker-namespace }}/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: workflow
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=git-
            type=raw,value=latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Extract metadata for Docker cache
        id: cache-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
          flavor: |
            prefix=cache-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=registry,ref=${{ steps.cache-meta.outputs.tags }}
          cache-to: type=registry,ref=${{ steps.cache-meta.outputs.tags }},mode=max
          build-args: |
            BUILD_HASH=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      actions: read
    environment: preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy NGINX Ingress Controller to ingress-nginx namespace
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.NGNIX_INGRESS_MANIFEST_URL }}
          namespace: ingress-nginx

      - name: Bake deployment
        uses: azure/k8s-bake@v3
        with:
          renderEngine: kustomize
          kustomizationPath: manifests/overlays/azure
          kubectl-version: latest
        id: bake

      - name: Deploy platform
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: efrei-dev-azure
