apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: efrei-dev-azure

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: pvc.patch.yaml
    target:
      kind: PersistentVolumeClaim
